# Generated by Django 2.2.5 on 2020-07-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topngNO', models.IntegerField()),
                ('small', models.IntegerField()),
                ('large', models.IntegerField()),
                ('itemname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemslist', to='ponopiza.category')),
            ],
        ),
        migrations.CreateModel(
            name='toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toppingname', models.CharField(max_length=64)),
                ('item', models.ManyToManyField(blank=True, related_name='toppings', to='ponopiza.items')),
            ],
        ),
    ]
