# Generated by Django 2.2.5 on 2020-07-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponopiza', '0002_items_itemsname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='itemname',
            new_name='cat',
        ),
    ]
