# Generated by Django 2.2.5 on 2020-07-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponopiza', '0003_auto_20200701_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='small',
            field=models.FloatField(),
        ),
    ]
